// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rib_to_asn_table
Rcpp::DataFrame rib_to_asn_table(std::string path, bool progress);
RcppExport SEXP mrt_rib_to_asn_table(SEXP pathSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    __result = Rcpp::wrap(rib_to_asn_table(path, progress));
    return __result;
END_RCPP
}
