# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert RouteViews RIB (bgpdump table dump v2) to subnet/asn map
#'
#' It presently ONLY works with the modern RouteViews v2 format.
#'
#' @param path path to RouteViews RIB (can be compressed)
#' @param progress if \code{TRUE} output a message every 50,000 records.
#' @return \code{tbl_df} (tibble) or \code{NULL}
#' @export
rib_to_asn_table <- function(path, progress = FALSE) {
    .Call('mrt_rib_to_asn_table', PACKAGE = 'mrt', path, progress)
}

